"""
Phase 1 Agent State Definition

This module defines the state structure for the Phase 1 Code Interpreter Agent.

Privacy-Preserving Architecture:
- The LLM (Cloud) NEVER sees the full CSV content
- The LLM ONLY sees bounded metadata (basename, size, columns, dtypes and shape)
- Metadata is synchronized after every successful code execution

State Management:
- sop_config: The loaded SOP JSON defining the workflow
- current_stage_id: Current stage in the SOP
- current_step_index: Current step within the stage
- execution_history: Log of all generated code and execution results
- data_summary: CRITICAL metadata about the current dataset
- context_variables: Dynamic variables (is_balanced, run_ml_pipeline, etc.)
- current_data_path: Local file path to the current dataset
"""

from typing import TypedDict, Optional, List, Dict, Any
import os
import json

from src.utils.config_manager import get_config
from src.utils.evaluation_audit import describe_path, write_audit_json


class ExecutionRecord(TypedDict):
    """
    Record of a single code execution.
    
    Fields:
        step_id: Identifier for the SOP step
        generated_code: The Python code generated by the LLM
        stdout: Standard output from execution
        stderr: Standard error from execution
        success: Whether execution succeeded
        execution_time: Time taken to execute (seconds)
        state_updates: Any state updates extracted from output
    """
    step_id: str
    generated_code: str
    stdout: str
    stderr: str
    success: bool
    execution_time: float
    state_updates: Optional[Dict[str, Any]]


class DataSummary(TypedDict):
    """
    Metadata summary of the current dataset.
    
    This is the ONLY data information the LLM sees - never the full CSV.
    
    Fields:
        columns: List of column names
        dtypes: Dictionary mapping column names to data types
        n_rows: Number of rows in the dataset
        n_cols: Number of columns in the dataset
        file_name: Basename only; local directories are never exposed to the LLM
        file_size_bytes: File size in bytes
        head_preview: Privacy policy marker; never contains row-level values
        missing_values: Dictionary of missing value counts per column
        target_column: Name of the target/group column (if applicable)
    """
    columns: List[str]
    dtypes: Dict[str, str]
    n_rows: int
    n_cols: int
    file_name: str
    file_size_bytes: int
    head_preview: str
    missing_values: Optional[Dict[str, int]]
    target_column: Optional[str]


class Phase1State(TypedDict):
    """
    State for Phase 1 Code Interpreter Agent.
    
    This state manages the execution of an SOP-driven data analysis workflow
    with privacy-preserving data handling.
    
    Privacy Architecture:
    - current_data_path: Local file path (LLM never accesses directly)
    - data_summary: Metadata only (filename, size, columns, types and shape)
    - The LLM generates code based on metadata, not raw data
    
    Metadata Synchronization:
    - After each successful execution, data_summary is refreshed
    - This ensures the LLM always knows current column names and data shape
    
    Magic Output Protocol:
    - Generated code prints JSON with "__METABO_UPDATE__" key
    - execute_node parses this and updates context_variables
    
    Fields:
        sop_config: The loaded SOP JSON configuration
        current_stage_id: Current stage identifier (e.g., "1", "2.1")
        current_step_index: Index of current step within the stage
        execution_history: List of all execution records
        data_summary: Metadata about the current dataset
        context_variables: Dynamic variables (is_balanced, protected_columns, etc.)
        current_data_path: Local file path to current dataset
        error: Error message if workflow fails
        completed: Whether the workflow has completed
        messages: List of messages for LLM conversation
    """
    # SOP Configuration
    sop_config: Dict[str, Any]
    current_stage_id: str
    current_step_index: int
    
    # Execution Tracking
    execution_history: List[ExecutionRecord]
    
    # Privacy-Preserving Data Information
    data_summary: DataSummary
    current_data_path: str
    
    # Dynamic Context
    context_variables: Dict[str, Any]
    dataset_fingerprint: Dict[str, Any]
    memory_context: Dict[str, Any]
    phase1_memory_pack: Dict[str, Any]
    error_fix_hints: List[Dict[str, Any]]
    memory_trace: Dict[str, Any]
    phase1_summary: Dict[str, Any]
    
    # Workflow Status
    error: Optional[str]
    completed: bool
    
    # LLM Conversation
    messages: List[Dict[str, str]]
    
    # LLM Instance
    llm: Optional[Any]  # Language model for code generation
    
    # Retry Configuration
    max_retries: int
    retry_count: int
    error_history: List[str]
    last_error: Optional[str]
    reflection_messages: List[Dict[str, str]]


def create_initial_state(
    sop_config: Dict[str, Any],
    initial_data_path: str,
    initial_data_summary: DataSummary,
    target_column: Optional[str] = None,
    max_retries: int = 3,
    llm: Optional[Any] = None,
    initial_context_variables: Optional[Dict[str, Any]] = None,
    dataset_fingerprint: Optional[Dict[str, Any]] = None,
    memory_context: Optional[Dict[str, Any]] = None,
    phase1_memory_pack: Optional[Dict[str, Any]] = None,
) -> Phase1State:
    """
    Create an initial Phase1State for a new workflow.
    
    Args:
        sop_config: The SOP configuration dictionary
        initial_data_path: Path to the initial dataset
        initial_data_summary: Metadata summary of the initial dataset
        target_column: Name of the target/group column (optional)
        max_retries: Maximum number of retry attempts per step (default: 3)
        llm: Language model for code generation (optional)
        initial_context_variables: Optional initial context variables injected from
            upstream stages (e.g. Phase 0 outputs / protected anchors)
        dataset_fingerprint: Optional dataset fingerprint for memory retrieval
        memory_context: Optional run-level memory context payload
        phase1_memory_pack: Optional advisory Phase 1 memory hints
    
    Returns:
        Initialized Phase1State
    
    Example:
        >>> sop = load_sop("data_cleaning.json")
        >>> summary = get_data_summary("data.csv")
        >>> llm = ChatOpenAI(model="gpt-4")
        >>> state = create_initial_state(sop, "data.csv", summary, "Group", max_retries=3, llm=llm)
    """
    # Set target column in data summary if provided
    if target_column:
        initial_data_summary["target_column"] = target_column
    
    cfg = get_config()
    phase1_config = cfg.get_phase1_config()
    feature_selection_config = phase1_config.get("feature_selection", {})
    base_context = {
        "protected_columns": [target_column] if target_column else [],
        "is_balanced": None,
        "run_ml_pipeline": True,  # Default: Use ML pipeline
        "run_traditional_stats": False,  # Default: Skip traditional stats
        "feature_selection_method": None,
        "model_type": None,
        "pre_engineering_data_path": None,
        "unscaled_enriched_data_path": None,
        "scaled_merged_data_path": None,
        "p0_bootstrap_completed": False,
        "phase1_stability_iterations": int(feature_selection_config.get("stability_iterations", 30) or 30),
        "phase1_resampling_fraction": float(feature_selection_config.get("resampling_fraction", 0.8) or 0.8),
        "phase1_final_panel_target_size": int(feature_selection_config.get("final_panel_target_size", 15) or 15),
        "phase1_per_method_select_k": int(feature_selection_config.get("per_method_select_k", 15) or 15),
        "phase1_selection_frequency_threshold": float(feature_selection_config.get("selection_frequency_threshold", 0.60) or 0.60),
        "phase1_method_consensus_threshold": int(feature_selection_config.get("method_consensus_threshold", 3) or 3),
        "phase1_max_pairwise_correlation": float(feature_selection_config.get("max_pairwise_correlation", 0.90) or 0.90),
        "phase1_min_final_feature_count": 8,
        "phase1_selector_family": [
            "run_elasticnet_selector",
            "run_lasso_selector",
            "run_random_forest_selector",
            "run_lightgbm_selector",
            "run_mrmr_selector",
            "run_t_test_selector",
            "run_fdr_effect_size_selector",
        ],
        "candidate_universe_path": None,
        "candidate_universe_metadata_path": None,
        "stability_summary_path": None,
        "stability_scores_path": None,
        "stable_core_path": None,
        "phase1_panel_selection_path": None,
        "stable_core_features": [],
    }
    if isinstance(initial_context_variables, dict):
        base_context.update(initial_context_variables)

    dataset_fingerprint = dict(dataset_fingerprint or {})
    memory_context = dict(memory_context or {})
    phase1_memory_pack = dict(phase1_memory_pack or {})

    return Phase1State(
        sop_config=sop_config,
        current_stage_id="0",  # Start at stage 0 (first stage)
        current_step_index=0,  # Start at first step
        execution_history=[],
        data_summary=initial_data_summary,
        current_data_path=initial_data_path,
        context_variables=base_context,
        dataset_fingerprint=dataset_fingerprint,
        memory_context=memory_context,
        phase1_memory_pack=phase1_memory_pack,
        error_fix_hints=[],
        memory_trace={},
        phase1_summary={},
        error=None,
        completed=False,
        messages=[],
        llm=llm,
        # Error Recovery Fields
        retry_count=0,
        max_retries=max_retries,
        last_error=None,
        error_history=[],
        reflection_messages=[],
    )


def evaluate_condition(condition: Optional[str], context_variables: Dict[str, Any]) -> bool:
    """
    Evaluate a stage condition.
    
    Args:
        condition: Condition string (e.g., "run_ml_pipeline == true")
        context_variables: Current context variables
    
    Returns:
        True if condition is met or no condition specified
    
    Supported condition formats:
        - "variable_name == true" or "variable_name == false"
        - "variable_name exists"
        - None (no condition, always execute)
    
    Examples:
        >>> evaluate_condition("run_ml_pipeline == true", {"run_ml_pipeline": True})
        True
        >>> evaluate_condition("phase0_output exists", {"phase0_output": {...}})
        True
        >>> evaluate_condition(None, {})
        True
    """
    if not condition:
        return True  # No condition means always execute
    
    try:
        # Pattern 1: "variable == true" or "variable == false"
        if " == " in condition:
            var_name, expected_value = condition.split(" == ")
            var_name = var_name.strip()
            expected_value = expected_value.strip()
            
            actual_value = context_variables.get(var_name)
            
            # Convert string "true"/"false" to boolean
            if expected_value.lower() == "true":
                expected_value = True
            elif expected_value.lower() == "false":
                expected_value = False
            
            return actual_value == expected_value
        
        # Pattern 2: "variable exists"
        elif " exists" in condition:
            var_name = condition.replace(" exists", "").strip()
            return var_name in context_variables and context_variables[var_name] is not None
        
        else:
            # Unknown condition format, log warning and default to True
            print(f"Warning: Unknown condition format '{condition}', defaulting to True")
            return True
    
    except Exception as e:
        # If condition evaluation fails, log error and default to True
        print(f"Warning: Failed to evaluate condition '{condition}': {e}, defaulting to True")
        return True


def get_current_step(state: Phase1State) -> Optional[Dict[str, Any]]:
    """
    Get the current step from the SOP configuration.
    
    Args:
        state: Current Phase1State
    
    Returns:
        Current step dictionary or None if no more steps
    
    Example:
        >>> step = get_current_step(state)
        >>> print(step["instruction"])
    """
    stage_id = state["current_stage_id"]
    step_index = state["current_step_index"]
    
    # Find the stage in SOP
    stages = state["sop_config"].get("stages", [])
    current_stage = None
    
    for stage in stages:
        if str(stage.get("id")) == str(stage_id):
            current_stage = stage
            break
    
    if not current_stage:
        return None
    
    # Get the step
    steps = current_stage.get("steps", [])
    if step_index >= len(steps):
        return None
    
    return steps[step_index]


def _read_phase1_tabular_file(path: str):
    import pandas as pd

    if path.endswith((".xlsx", ".xls")):
        return pd.read_excel(path)
    return pd.read_csv(path)


def _write_phase1_tabular_file(df, path: str) -> None:
    if path.endswith((".xlsx", ".xls")):
        df.to_excel(path, index=False)
    else:
        df.to_csv(path, index=False)


def _apply_train_fitted_standard_scaling(train_df, holdout_df, protected_cols):
    """
    Fit scaling statistics on the training pool only, then transform both sides.

    This keeps Stage 5 feature-selection and downstream holdout evaluation free
    from train/holdout contamination even if Stage 1.5 already materialized a
    globally scaled file for legacy consumers.
    """
    import pandas as pd

    train_scaled = train_df.copy()
    holdout_scaled = holdout_df.copy()
    protected_set = {col for col in protected_cols if col in train_df.columns}

    numeric_features = [
        col
        for col in train_df.columns
        if col not in protected_set and pd.api.types.is_numeric_dtype(train_df[col])
    ]

    scaling_stats: Dict[str, Dict[str, float]] = {}
    for col in numeric_features:
        train_series = pd.to_numeric(train_df[col], errors="coerce")
        holdout_series = pd.to_numeric(holdout_df[col], errors="coerce")

        mean_value = float(train_series.mean())
        std_value = float(train_series.std(ddof=0))
        if not std_value or abs(std_value) < 1e-12:
            std_value = 1.0

        train_scaled[col] = (train_series - mean_value) / std_value
        holdout_scaled[col] = (holdout_series - mean_value) / std_value
        scaling_stats[col] = {"mean": mean_value, "std": std_value}

    return train_scaled, holdout_scaled, scaling_stats


def _maybe_materialize_unscaled_enriched_snapshot(state: Phase1State) -> Phase1State:
    """
    Preserve the canonical pre-engineering snapshot for downstream split logic.

    Sensitive engineered features are regenerated after the train/holdout split.
    Do not rebuild a full-dataset engineered snapshot here, otherwise label- or
    full-data-dependent feature selection can leak across the split boundary.
    """
    context_variables = dict(state.get("context_variables", {}))
    pre_engineering_data_path = str(context_variables.get("pre_engineering_data_path", "") or "").strip()
    if not pre_engineering_data_path or not os.path.exists(pre_engineering_data_path):
        return state

    context_variables.update({
        "unscaled_enriched_data_path": pre_engineering_data_path,
        "unscaled_enriched_metadata_path": "",
        "engineered_feature_generation_policy": "train_only_after_split",
    })
    print(f"[Leakage Guard] ✅ Using pre-engineering snapshot as split source: {pre_engineering_data_path}")
    return {
        **state,
        "context_variables": context_variables,
    }


def _resolve_holdout_target_column(df, requested_target):
    """Resolve a missing CLI target for leakage-audit split materialization.

    Some legacy datasets expose the outcome as ``group`` while an older CLI
    invocation may pass a stale target name (for example ``Factors``).  The
    modelling pipeline already records its canonical target downstream; this
    resolver is only used to materialize the train/holdout audit sidecars.
    """
    requested = str(requested_target or "").strip()
    if requested and requested in df.columns:
        return requested, False
    normalized = {str(col).strip().lower(): str(col) for col in df.columns}
    for candidate in ("group", "target", "label", "class", "outcome", "y"):
        if candidate in normalized:
            return normalized[candidate], True
    if requested:
        return requested, False
    return "", False


def _maybe_create_phase1_holdout_split(state: Phase1State) -> Phase1State:
    """
    Create a leakage-safe train/holdout split after Stage 1.5 completes.

    The split happens on the pre-engineering matrix. Any engineered feature that
    depends on labels or full-data statistics is regenerated using the train pool
    only, then projected onto the holdout pool.
    """
    context_variables = dict(state.get("context_variables", {}))
    if context_variables.get("holdout_split_created"):
        return state

    current_data_path = str(state.get("current_data_path", "") or "").strip()
    target_column = state.get("data_summary", {}).get("target_column")
    if not current_data_path or not target_column or not os.path.exists(current_data_path):
        return state

    try:
        from sklearn.model_selection import train_test_split
        from src.agents.phase1.nodes import get_data_summary
        from src.utils.config_manager import get_config
        from src.tools.domain.feature_generator import generate_train_only_engineered_feature_bundle

        candidate_source_paths = [
            str(context_variables.get("pre_engineering_data_path", "") or "").strip(),
            str(context_variables.get("unscaled_enriched_data_path", "") or "").strip(),
            current_data_path,
        ]
        source_data_path = next(
            (path for path in candidate_source_paths if path and os.path.exists(path)),
            current_data_path,
        )

        df = _read_phase1_tabular_file(source_data_path)

        # Synthetic row IDs are only for temporary merge alignment and should
        # not be carried into train/holdout pool artifacts.
        if "__row_id__" in df.columns:
            df = df.drop(columns=["__row_id__"])

        requested_target_column = str(target_column or "").strip()
        target_column, target_was_inferred = _resolve_holdout_target_column(df, requested_target_column)
        if target_column not in df.columns:
            print(f"[Leakage Guard] Skip holdout split: target column '{requested_target_column}' not found and no fallback label column is available")
            return state
        if target_was_inferred:
            print(f"[Leakage Guard] ⚠️ Requested target '{requested_target_column}' was not found; using detected audit target '{target_column}'")
            context_variables.update({
                "holdout_split_requested_target_column": requested_target_column,
                "holdout_split_target_column": target_column,
                "holdout_split_target_inferred": True,
            })

        if len(df) < 20:
            print(f"[Leakage Guard] Skip holdout split: dataset too small ({len(df)} rows)")
            return state

        cfg = get_config()
        latest_dir = cfg.get_phase1_path("intermediate_latest_dir") or "output/phase1/intermediate/latest"
        engineered_dir = os.path.join(latest_dir, "engineered")
        final_dir = cfg.get_phase1_path("final_dir") or "output/phase1/final"
        os.makedirs(engineered_dir, exist_ok=True)
        os.makedirs(final_dir, exist_ok=True)
        train_path = os.path.join(final_dir, "selected_features_train_pool.csv")
        holdout_path = os.path.join(final_dir, "selected_features_holdout_pool.csv")
        train_raw_path = os.path.join(engineered_dir, "train_pool_pre_engineering.csv")
        holdout_raw_path = os.path.join(engineered_dir, "holdout_pool_pre_engineering.csv")
        train_only_bundle_dir = os.path.join(engineered_dir, "train_only_bundle")
        train_only_registry_path = cfg.get_phase1_path("engineered_feature_registry") or os.path.join(
            engineered_dir,
            "engineered_feature_registry.json",
        )

        train_df, holdout_df = train_test_split(
            df,
            test_size=0.2,
            stratify=df[target_column],
            random_state=int(os.environ.get("METABOAGENT_RANDOM_STATE", "42")),
        )
        train_df = train_df.reset_index(drop=True)
        holdout_df = holdout_df.reset_index(drop=True)
        _write_phase1_tabular_file(train_df, train_raw_path)
        _write_phase1_tabular_file(holdout_df, holdout_raw_path)

        engineering_result = generate_train_only_engineered_feature_bundle(
            train_data_path=train_raw_path,
            holdout_data_path=holdout_raw_path,
            output_dir=train_only_bundle_dir,
            phase0_output=context_variables.get("phase0_output"),
            registry_path=train_only_registry_path,
            rules_path=context_variables.get("engineered_feature_rules_path"),
        )
        if not isinstance(engineering_result, dict) or engineering_result.get("status") != "success":
            raise ValueError(f"train-only engineered feature bundle failed: {engineering_result}")

        train_engineered_df = _read_phase1_tabular_file(engineering_result["train_merged_path"])
        holdout_engineered_df = _read_phase1_tabular_file(engineering_result["holdout_merged_path"])
        protected_candidates = {
            "Sample_ID",
            "sample_id",
            "SampleID",
            "sampleid",
            "ROW_ID",
            "row_id",
            "__row_id__",
            "ID",
            "id",
            target_column,
        }
        protected_cols = [col for col in train_engineered_df.columns if col in protected_candidates]
        train_scaled_df, holdout_scaled_df, scaling_stats = _apply_train_fitted_standard_scaling(
            train_df=train_engineered_df,
            holdout_df=holdout_engineered_df,
            protected_cols=protected_cols,
        )

        _write_phase1_tabular_file(train_scaled_df, train_path)
        _write_phase1_tabular_file(holdout_scaled_df, holdout_path)

        context_variables.update({
            "holdout_split_created": True,
            "holdout_data_path": holdout_path,
            "train_pool_data_path": train_path,
            "holdout_pre_engineering_data_path": holdout_raw_path,
            "train_pool_pre_engineering_data_path": train_raw_path,
            "train_pool_unscaled_engineered_data_path": engineering_result["train_merged_path"],
            "holdout_unscaled_engineered_data_path": engineering_result["holdout_merged_path"],
            "engineered_feature_registry_path": engineering_result["registry_path"],
            "train_only_engineering_summary_path": engineering_result["summary_path"],
            "holdout_size": int(len(holdout_scaled_df)),
            "train_size": int(len(train_scaled_df)),
            "split_strategy": "pre_engineering_split_train_only_engineering_train_fit_scaled",
            "step50_split_source_path": source_data_path,
            "train_fit_scaling_applied": True,
            "train_fit_scaling_method": "standard",
            "train_fit_scaling_feature_count": int(len(scaling_stats)),
            "n_ratio_features": int((engineering_result.get("counts", {}) or {}).get("train_ratio_features", 0) or 0),
            "n_sum_features": int((engineering_result.get("counts", {}) or {}).get("train_taxonomy_features", 0) or 0),
            "n_pathway_scores": int((engineering_result.get("counts", {}) or {}).get("train_pathway_features", 0) or 0),
            "engineered_features_merged": True,
            "unscaled_enriched_data_path": engineering_result["train_merged_path"],
        })

        print("[Leakage Guard] ✅ Created train/holdout split before Stage 5")
        print(f"[Leakage Guard] Split source: {source_data_path}")
        print(f"[Leakage Guard] Train-only engineering bundle: {engineering_result['summary_path']}")
        print(f"[Leakage Guard] Train pool: {train_path} ({train_scaled_df.shape[0]} rows)")
        print(f"[Leakage Guard] Holdout pool: {holdout_path} ({holdout_scaled_df.shape[0]} rows)")
        print(f"[Leakage Guard] Train-fitted scaling applied to {len(scaling_stats)} numeric features")

        # Observational audit sidecars.  These record the completed pipeline;
        # they never feed values back into Phase 1 decisions.
        split_seed = int(os.environ.get("METABOAGENT_RANDOM_STATE", "42"))
        split_evidence = {
            "assessment_domain": "data_split",
            "status": "PASS",
            "split_strategy": "stratified_train_test_split_before_engineering",
            "random_state": split_seed,
            "test_size": 0.2,
            "stratify_target": target_column,
            "requested_target_column": requested_target_column,
            "target_column_inferred": bool(target_was_inferred),
            "source": describe_path(source_data_path),
            "train_pre_engineering": describe_path(train_raw_path),
            "holdout_pre_engineering": describe_path(holdout_raw_path),
            "train_final": describe_path(train_path),
            "holdout_final": describe_path(holdout_path),
            "train_rows": int(len(train_scaled_df)),
            "holdout_rows": int(len(holdout_scaled_df)),
        }
        write_audit_json("data_split_audit.json", split_evidence)
        write_audit_json("preprocessing_audit.json", {
            "assessment_domain": "preprocessing",
            "status": "PASS",
            "operations": [{
                "name": "standard_scaling",
                "fit_scope": "train_only",
                "transform_scope": "train_and_holdout",
                "label_used": False,
                "feature_count": int(len(scaling_stats)),
                "fit_input": describe_path(engineering_result["train_merged_path"]),
                "transform_input": describe_path(engineering_result["holdout_merged_path"]),
                "parameters": scaling_stats,
            }],
        })
        write_audit_json("feature_engineering_audit.json", {
            "assessment_domain": "feature_engineering",
            "status": "PASS",
            "policy": "train_only_after_split",
            "label_used_for_engineering": False,
            "train_only_bundle": describe_path(engineering_result["summary_path"]),
            "feature_registry": describe_path(engineering_result["registry_path"]),
            "feature_counts": engineering_result.get("counts", {}),
            "train_output": describe_path(engineering_result["train_merged_path"]),
            "holdout_output": describe_path(engineering_result["holdout_merged_path"]),
        })

        return {
            **state,
            "current_data_path": train_path,
            "data_summary": get_data_summary(train_path, target_column),
            "context_variables": context_variables,
        }
    except Exception as e:
        print(f"[Leakage Guard] ⚠️ Warning: failed to create holdout split: {e}")
        return state


def _maybe_run_phase1_p0_bootstrap(state: Phase1State) -> Phase1State:
    """
    Run the targeted preprocessing P0 chain programmatically after Stage 0.

    This removes the dependency on LLM availability for:
    - preprocessing_context.json
    - zero_pattern_report.json
    - missingness_report.json
    - preprocessing_report.json
    - preprocessing_decision_pack.json
    """
    context_variables = dict(state.get("context_variables", {}))
    if context_variables.get("p0_bootstrap_completed"):
        return state

    current_data_path = state.get("current_data_path", "")
    if not current_data_path or not os.path.exists(current_data_path):
        print(f"[P0 Bootstrap] Skip: invalid current_data_path: {current_data_path}")
        return state

    try:
        from pathlib import Path
        from src.utils.config_manager import get_config
        from src.agents.phase1.nodes import get_data_summary
        from src.tools.analysis.data_analysis_tools import (
            data_context_resolver_tool,
            zero_semantics_analyzer_tool,
            missingness_assessment_tool,
            preprocessing_qa_reporter_tool,
        )

        cfg = get_config()
        latest_dir = cfg.get_phase1_path("intermediate_latest_dir") or "output/phase1/intermediate/latest"
        os.makedirs(latest_dir, exist_ok=True)

        study_metadata_path = str(context_variables.get("study_metadata_path", "") or "").strip()
        column_roles_path = str(context_variables.get("column_roles_path", "") or "").strip()
        dataset_source = str(context_variables.get("dataset_source", "") or "").strip()
        user_declared_data_level = str(context_variables.get("user_declared_data_level", "") or "").strip()
        protected_columns = list(dict.fromkeys([
            *[str(col) for col in (context_variables.get("protected_columns") or []) if str(col).strip()],
            *[str(col) for col in ["Sample_ID", "sample_id", "SampleID", "sampleid",
                                   "ROW_ID", "row_id", "__row_id__",
                                   state.get("data_summary", {}).get("target_column")]
              if isinstance(col, str) and col.strip()],
        ]))

        context_report_path = os.path.join(latest_dir, "preprocessing_context.json")
        zero_report_path = os.path.join(latest_dir, "zero_pattern_report.json")
        missingness_report_path = os.path.join(latest_dir, "missingness_report.json")

        context_report = json.loads(data_context_resolver_tool(
            dataset_path=current_data_path,
            study_metadata_path=study_metadata_path,
            column_roles_path=column_roles_path,
            source_hint=dataset_source,
            user_declared_data_level=user_declared_data_level,
        ))
        if not context_report.get("success"):
            raise ValueError(f"data_context_resolver_tool failed: {context_report.get('error', 'unknown error')}")
        Path(context_report_path).write_text(
            json.dumps(context_report, ensure_ascii=False, indent=2) + "\n",
            encoding="utf-8",
        )

        merged_protected_columns = list(dict.fromkeys(
            protected_columns + list(context_report.get("protected_columns", []))
        ))

        zero_report = json.loads(zero_semantics_analyzer_tool(
            dataset_path=current_data_path,
            context_report_path=context_report_path,
            study_metadata_path=study_metadata_path,
            protected_columns=merged_protected_columns,
        ))
        if not zero_report.get("success"):
            raise ValueError(f"zero_semantics_analyzer_tool failed: {zero_report.get('error', 'unknown error')}")
        Path(zero_report_path).write_text(
            json.dumps(zero_report, ensure_ascii=False, indent=2) + "\n",
            encoding="utf-8",
        )

        missingness_report = json.loads(missingness_assessment_tool(
            dataset_path=current_data_path,
            context_report_path=context_report_path,
            zero_pattern_report_path=zero_report_path,
            zero_handling_mode="auto",
            protected_columns=merged_protected_columns,
        ))
        if not missingness_report.get("success"):
            raise ValueError(f"missingness_assessment_tool failed: {missingness_report.get('error', 'unknown error')}")
        Path(missingness_report_path).write_text(
            json.dumps(missingness_report, ensure_ascii=False, indent=2) + "\n",
            encoding="utf-8",
        )

        qa_payload = json.loads(preprocessing_qa_reporter_tool(
            context_report_path=context_report_path,
            zero_pattern_report_path=zero_report_path,
            missingness_report_path=missingness_report_path,
        ))
        if not qa_payload.get("success"):
            raise ValueError(f"preprocessing_qa_reporter_tool failed: {qa_payload.get('error', 'unknown error')}")

        context_variables.update({
            "p0_bootstrap_completed": True,
            "preprocessing_context_report_path": context_report_path,
            "zero_pattern_report_path": zero_report_path,
            "missingness_report_path": missingness_report_path,
            "preprocessing_report_path": qa_payload.get("preprocessing_report_path"),
            "preprocessing_summary_path": qa_payload.get("preprocessing_summary_path"),
            "preprocessing_decision_pack_path": qa_payload.get("preprocessing_decision_pack_path"),
            "preprocessing_branch_used": qa_payload.get("branch_used"),
            "phase4_reportable_facts": qa_payload.get("phase4_reportable_facts", {}),
            "platform_source": context_report.get("platform_source"),
            "data_level": context_report.get("data_level"),
            "candidate_branch": context_report.get("candidate_branch"),
            "has_pooled_qc": context_report.get("has_pooled_qc"),
            "has_blank_samples": context_report.get("has_blank_samples"),
            "has_run_order": context_report.get("has_run_order"),
            "has_batch_metadata": context_report.get("has_batch_metadata"),
            "protected_columns": merged_protected_columns,
            "zero_semantics_status": zero_report.get("zero_semantics_status"),
            "zero_handling_strategy": zero_report.get("suggested_zero_handling"),
            "zero_evidence_flags": zero_report.get("evidence_flags", []),
            "zero_handling_mode_used": missingness_report.get("zero_handling_mode_used"),
            "suspected_missingness_mechanism": missingness_report.get("suspected_mechanism"),
            "recommended_imputation_family": missingness_report.get("recommended_imputation_family"),
            "recommended_missingness_thresholds": missingness_report.get("recommended_thresholds", {}),
            "left_censoring_signals": missingness_report.get("left_censoring_signals", []),
        })

        print("[P0 Bootstrap] ✅ Exported targeted preprocessing artifacts")
        print(f"[P0 Bootstrap] Context: {context_report_path}")
        print(f"[P0 Bootstrap] Zero semantics: {zero_report_path}")
        print(f"[P0 Bootstrap] Missingness: {missingness_report_path}")
        print(f"[P0 Bootstrap] QA report: {qa_payload.get('preprocessing_report_path')}")

        updated_state = {
            **state,
            "context_variables": context_variables,
        }
        updated_state["data_summary"] = get_data_summary(
            updated_state["current_data_path"],
            updated_state.get("data_summary", {}).get("target_column"),
        )
        return updated_state
    except Exception as e:
        print(f"[P0 Bootstrap] ⚠️ Warning: bootstrap failed, will fall back to Stage 0.5 LLM path: {e}")
        return {
            **state,
            "context_variables": {
                **context_variables,
                "p0_bootstrap_completed": False,
                "p0_bootstrap_error": str(e),
            },
        }


def advance_to_next_step(state: Phase1State) -> Phase1State:
    """
    Advance the state to the next step in the SOP.
    
    Args:
        state: Current Phase1State
    
    Returns:
        Updated Phase1State with next step
    
    Logic:
        1. Try to advance to next step in current stage
        2. If no more steps in stage, advance to next stage (checking conditions)
        3. Skip stages whose conditions are not met
        4. If no more stages, mark workflow as completed
        5. Reset retry_count when advancing to new step
    """
    stage_id = state["current_stage_id"]
    step_index = state["current_step_index"]
    context_variables = state["context_variables"]
    
    # Find current stage
    stages = state["sop_config"].get("stages", [])
    current_stage_idx = None
    current_stage = None
    
    for idx, stage in enumerate(stages):
        if str(stage.get("id")) == str(stage_id):
            current_stage_idx = idx
            current_stage = stage
            break
    
    if not current_stage:
        # No current stage found, mark as completed
        print(f"[advance_to_next_step] No current stage found for stage_id={stage_id}, marking as completed")
        return {**state, "completed": True}
    
    # Check if there are more steps in current stage (with condition checking)
    steps = current_stage.get("steps", [])
    
    # Search for next step with satisfied condition
    for next_step_idx in range(step_index + 1, len(steps)):
        candidate_step = steps[next_step_idx]
        step_condition = candidate_step.get("condition")
        step_id_candidate = candidate_step.get("step_id", candidate_step.get("id", f"step_{next_step_idx}"))
        
        # Evaluate step condition
        condition_met = evaluate_condition(step_condition, context_variables)
        
        print(f"[advance_to_next_step] Checking Step {step_id_candidate} in Stage {stage_id}:")
        print(f"  - Condition: {step_condition}")
        if step_condition:  # Only show relevant context variables if there's a condition
            print(f"  - Context variables: is_balanced={context_variables.get('is_balanced')}, run_traditional_stats={context_variables.get('run_traditional_stats')}, run_ml_pipeline={context_variables.get('run_ml_pipeline')}")
        print(f"  - Condition met: {condition_met}")
        
        if condition_met:
            # Found a step with satisfied condition
            print(f"[advance_to_next_step] ✓ Step {step_id_candidate} condition satisfied, advancing to it")
            return {
                **state,
                "current_step_index": next_step_idx,
                "retry_count": 0,  # Reset retry count for new step
                "error_history": []  # Clear error history for new step
            }
        else:
            # Skip this step
            print(f"[advance_to_next_step] ✗ Step {step_id_candidate} condition NOT satisfied, skipping")
    
    # No more steps with satisfied conditions in current stage, continue to next stage search
    
    # No more steps in current stage, find next stage with satisfied condition
    print(f"[advance_to_next_step] Stage {stage_id} completed, searching for next stage...")

    if str(stage_id) == "0":
        state = _maybe_run_phase1_p0_bootstrap(state)
        context_variables = state["context_variables"]
    
    # ========================================================================
    # Stage 1.5 后处理：工程特征接回 + 列名标准化
    # 设计原则：配置优先、状态感知、避免硬编码旧路径
    # ========================================================================
    if str(stage_id) == "1.5":
        print(f"\n{'='*80}")
        print("[Feature Merge] Stage 1.5 post-hook")
        print(f"{'='*80}")
        try:
            import os
            import pandas as pd

            def _load_df(path: str) -> pd.DataFrame:
                if path.endswith((".xlsx", ".xls")):
                    return pd.read_excel(path)
                return pd.read_csv(path)

            def _save_df(df: pd.DataFrame, path: str) -> None:
                if path.endswith((".xlsx", ".xls")):
                    df.to_excel(path, index=False)
                else:
                    df.to_csv(path, index=False)

            def _norm_abs(path: str) -> str:
                if not path:
                    return ""
                return os.path.abspath(path)

            def _resolve_engineered_candidates(current_data_path: str) -> List[str]:
                candidates: List[str] = []

                # 1) 来自上下文变量（若步骤中显式产出）
                ctx = state.get("context_variables", {})
                for key in ("engineered_features_path", "latest_engineered_features_path"):
                    p = ctx.get(key)
                    if isinstance(p, str) and p.strip():
                        candidates.append(_norm_abs(p.strip()))

                # 2) 来自配置（优先新目录结构）
                try:
                    from src.utils.config_manager import get_config
                    cfg = get_config()
                    phase1_paths = cfg.get_phase1_paths()
                    latest_dir = phase1_paths.get("intermediate_latest_dir", "")
                    if latest_dir:
                        candidates.append(
                            _norm_abs(os.path.join(latest_dir, "engineered", "data_with_engineered_features.csv"))
                        )
                except Exception:
                    pass

                # 3) 与 current_data_path 同目录下的常见文件名
                if current_data_path:
                    parent_dir = os.path.dirname(_norm_abs(current_data_path))
                    candidates.append(_norm_abs(os.path.join(parent_dir, "data_with_engineered_features.csv")))

                # 4) 兼容旧路径（最后兜底）
                candidates.append(_norm_abs("data/data_with_engineered_features.csv"))

                # 去重、过滤存在文件、排除当前文件自身
                seen = set()
                current_abs = _norm_abs(current_data_path)
                resolved: List[str] = []
                for p in candidates:
                    if not p or p in seen:
                        continue
                    seen.add(p)
                    if p == current_abs:
                        continue
                    if os.path.exists(p):
                        resolved.append(p)
                return resolved

            current_data_path = state.get("current_data_path", "")
            current_data_abs = _norm_abs(current_data_path)
            already_merged = bool(state.get("context_variables", {}).get("engineered_features_merged"))
            target_column = state.get("data_summary", {}).get("target_column")

            # current_data_path 已经是 engineered 成果文件时，不再重复后处理合并
            current_path_norm = current_data_abs.replace("\\", "/").lower()
            current_is_engineered = (
                "/engineered/" in current_path_norm
                or "data_with_engineered_features" in os.path.basename(current_path_norm)
            )

            if not current_data_abs or not os.path.exists(current_data_abs):
                print(f"[Feature Merge] Current data path is invalid: {current_data_path}")
            elif already_merged or current_is_engineered:
                reason = "context flag engineered_features_merged=True" if already_merged else "current_data_path already points to engineered dataset"
                print(f"[Feature Merge] Skip post-merge ({reason})")
                print(f"[Feature Merge] current_data_path: {current_data_abs}")
            else:
                df_current = _load_df(current_data_abs)
                print(f"[Feature Merge] Current dataset shape: {df_current.shape}")

                candidates = _resolve_engineered_candidates(current_data_abs)
                print(f"[Feature Merge] Candidate files: {len(candidates)}")

                best_plan = None
                protected_for_merge = {"Sample_ID", "sample_id", "SampleID", "sampleid", "ROW_ID", "row_id", "__row_id__", "Group"}
                if target_column:
                    protected_for_merge.add(target_column)

                for candidate_path in candidates:
                    try:
                        df_engineered = _load_df(candidate_path)
                    except Exception as e:
                        print(f"[Feature Merge] Skip unreadable candidate: {candidate_path} ({e})")
                        continue

                    # 选择 join key（泛化：优先样本ID列，再 target，再 Group）
                    join_key = None
                    for key in ("Sample_ID", "sample_id", "SampleID", "sampleid", "ROW_ID", "row_id", "__row_id__", target_column, "Group"):
                        if key and key in df_current.columns and key in df_engineered.columns:
                            join_key = key
                            break

                    # 行数不同且无 join key -> 跳过，防止索引拼接污染 NaN
                    if join_key is None and len(df_current) != len(df_engineered):
                        print(
                            "[Feature Merge] Skip candidate due to row mismatch without join key: "
                            f"{candidate_path} (current={len(df_current)}, engineered={len(df_engineered)})"
                        )
                        continue

                    new_feature_cols = [
                        col for col in df_engineered.columns
                        if col not in df_current.columns and col not in protected_for_merge
                    ]
                    if not new_feature_cols:
                        continue

                    score = len(new_feature_cols)
                    if best_plan is None or score > best_plan["score"]:
                        best_plan = {
                            "path": candidate_path,
                            "join_key": join_key,
                            "new_feature_cols": new_feature_cols,
                            "score": score,
                            "engineered_shape": df_engineered.shape,
                        }

                if best_plan is None:
                    print("[Feature Merge] No valid engineered file found for safe merge.")
                else:
                    candidate_path = best_plan["path"]
                    join_key = best_plan["join_key"]
                    new_feature_cols = best_plan["new_feature_cols"]
                    df_engineered = _load_df(candidate_path)

                    print(f"[Feature Merge] Selected candidate: {candidate_path}")
                    print(f"[Feature Merge] Engineered dataset shape: {best_plan['engineered_shape']}")
                    print(f"[Feature Merge] New features to merge: {len(new_feature_cols)}")

                    if join_key:
                        merge_cols = [join_key] + new_feature_cols
                        df_merged = df_current.merge(
                            df_engineered[merge_cols],
                            on=join_key,
                            how="left",
                        )
                    else:
                        # 仅当行数一致且无 join key 时按索引拼接
                        df_merged = pd.concat([df_current, df_engineered[new_feature_cols]], axis=1)

                    _save_df(df_merged, current_data_abs)
                    print(f"[Feature Merge] ✅ Successfully merged {len(new_feature_cols)} engineered features")
                    print(f"[Feature Merge] Updated dataset shape: {df_merged.shape}")
                    print(f"[Feature Merge] Saved to: {current_data_abs}")

                    from src.agents.phase1.nodes import get_data_summary
                    updated_summary = get_data_summary(current_data_abs, target_column)
                    updated_context = dict(state.get("context_variables", {}))
                    updated_context["engineered_features_merged"] = True
                    state = {
                        **state,
                        "data_summary": updated_summary,
                        "current_data_path": current_data_abs,
                        "context_variables": updated_context,
                    }

        except Exception as e:
            print(f"[Feature Merge] ⚠️  Warning: Failed in Stage 1.5 post-hook merge: {e}")
            import traceback
            traceback.print_exc()

        print(f"{'='*80}\n")

        state = _maybe_materialize_unscaled_enriched_snapshot(state)

        # ====================================================================
        # Leakage guard: split full processed matrix into train/holdout before
        # any supervised feature selection starts.
        # ====================================================================
        state = _maybe_create_phase1_holdout_split(state)

        # ====================================================================
        # Step 3: 方案 A - 源头标准化所有特征列名（LightGBM 兼容性）
        # ====================================================================
        print(f"\n{'='*80}")
        print(f"[Feature Standardization] Standardizing all feature column names")
        print(f"{'='*80}")
        
        try:
            from src.utils.feature_name_standardizer import standardize_feature_name
            import pandas as pd
            import os

            def _load_df(path: str) -> pd.DataFrame:
                if path.endswith((".xlsx", ".xls")):
                    return pd.read_excel(path)
                return pd.read_csv(path)

            def _save_df(df: pd.DataFrame, path: str) -> None:
                if path.endswith((".xlsx", ".xls")):
                    df.to_excel(path, index=False)
                else:
                    df.to_csv(path, index=False)

            def _drop_protected_alias_columns(
                df: pd.DataFrame,
                protected_cols: set[str],
            ) -> tuple[pd.DataFrame, List[str]]:
                protected_clean = {
                    standardize_feature_name(col)
                    for col in protected_cols
                    if col
                }
                duplicate_cols: List[str] = []

                for col in list(df.columns):
                    if col in protected_cols:
                        continue
                    cleaned = standardize_feature_name(col)
                    cleaned_base = cleaned.rsplit("_", 1)[0] if cleaned.rsplit("_", 1)[-1].isdigit() else cleaned
                    if cleaned in protected_clean or cleaned_base in protected_clean:
                        duplicate_cols.append(col)

                if duplicate_cols:
                    df = df.drop(columns=duplicate_cols, errors="ignore")
                return df, duplicate_cols
            
            current_data_path = state.get("current_data_path", "")
            context_vars = state.get("context_variables", {})

            def _standardize_dataset_in_place(
                dataset_path: str,
                protected_columns: set[str],
                label: str,
            ) -> None:
                df_local = _load_df(dataset_path)
                print(f"[Feature Standardization] {label} shape: {df_local.shape}")
                print(f"[Feature Standardization] {label} original columns: {len(df_local.columns)}")

                df_local, duplicate_protected_cols = _drop_protected_alias_columns(
                    df_local,
                    protected_columns,
                )
                for dup_col in duplicate_protected_cols:
                    print(f"[Feature Standardization]   Dropped protected alias column from {label}: {dup_col}")

                column_mapping = {}
                standardized_count = 0
                for col in df_local.columns:
                    if col in protected_columns:
                        column_mapping[col] = col
                    else:
                        standardized_name = standardize_feature_name(col)
                        column_mapping[col] = standardized_name
                        if col != standardized_name:
                            standardized_count += 1
                            print(f"[Feature Standardization]   {label}: {col} → {standardized_name}")

                df_local.rename(columns=column_mapping, inplace=True)
                _save_df(df_local, dataset_path)

                print(f"\n[Feature Standardization] ✅ {label} standardization complete:")
                print(f"  - Total columns: {len(df_local.columns)}")
                print(f"  - Protected columns: {len(protected_columns)} ({', '.join(protected_columns)})")
                print(f"  - Standardized columns: {standardized_count}")
                print(f"  - Saved to: {dataset_path}")

            if current_data_path and os.path.exists(current_data_path):
                target_column = state.get("data_summary", {}).get("target_column")
                protected_columns = {
                    'Sample_ID', 'sample_id', 'SampleID', 'sampleid',
                    'ROW_ID', 'row_id', '__row_id__',
                    'id', 'ID',
                    'Group', 'group', 'target', 'Target',
                    'Factors', 'factors', 'factor', 'FACTOR',
                }
                if target_column:
                    protected_columns.add(target_column)

                datasets_to_standardize: List[tuple[str, str]] = [
                    (current_data_path, "current/train dataset"),
                ]
                holdout_data_path = context_vars.get("holdout_data_path", "")
                train_pool_data_path = context_vars.get("train_pool_data_path", "")
                if train_pool_data_path and train_pool_data_path != current_data_path:
                    datasets_to_standardize.append((train_pool_data_path, "train pool"))
                if holdout_data_path:
                    datasets_to_standardize.append((holdout_data_path, "holdout pool"))

                seen_dataset_paths = set()
                for dataset_path, label in datasets_to_standardize:
                    abs_dataset_path = os.path.abspath(dataset_path)
                    if abs_dataset_path in seen_dataset_paths or not os.path.exists(abs_dataset_path):
                        continue
                    seen_dataset_paths.add(abs_dataset_path)
                    _standardize_dataset_in_place(abs_dataset_path, protected_columns, label)

                # 同时标准化候选工程特征文件（若存在）
                aux_candidates = [
                    os.path.abspath(os.path.join(os.path.dirname(current_data_path), "data_with_engineered_features.csv")),
                    os.path.abspath("data/data_with_engineered_features.csv"),
                ]
                seen_aux = set()
                for engineered_path in aux_candidates:
                    if engineered_path in seen_aux or not os.path.exists(engineered_path):
                        continue
                    seen_aux.add(engineered_path)
                    try:
                        _standardize_dataset_in_place(engineered_path, protected_columns, "aux engineered dataset")
                    except Exception as e:
                        print(f"  - Skip standardizing {engineered_path}: {e}")

                # 更新 state 中的 data_summary（使用标准化后的列名）
                from src.agents.phase1.nodes import get_data_summary
                updated_summary = get_data_summary(current_data_path, target_column)
                state = {**state, "data_summary": updated_summary}

            else:
                print(f"[Feature Standardization] ⚠️  Current data path not found: {current_data_path}")
        
        except Exception as e:
            print(f"[Feature Standardization] ⚠️  Warning: Failed to standardize feature names: {e}")
            import traceback
            traceback.print_exc()
        
        print(f"{'='*80}\n")
    
    for next_idx in range(current_stage_idx + 1, len(stages)):
        candidate_stage = stages[next_idx]
        candidate_stage_id = str(candidate_stage.get("id"))
        candidate_condition = candidate_stage.get("condition")
        
        # Evaluate condition
        condition_met = evaluate_condition(candidate_condition, context_variables)
        
        print(f"[advance_to_next_step] Checking Stage {candidate_stage_id}:")
        print(f"  - Condition: {candidate_condition}")
        print(f"  - Context variables: run_traditional_stats={context_variables.get('run_traditional_stats')}, run_ml_pipeline={context_variables.get('run_ml_pipeline')}")
        print(f"  - Condition met: {condition_met}")
        
        if condition_met:
            # Found a stage with satisfied condition
            print(f"[advance_to_next_step] ✓ Stage {candidate_stage_id} condition satisfied, advancing to it")
            return {
                **state,
                "current_stage_id": candidate_stage_id,
                "current_step_index": 0,
                "retry_count": 0,
                "error_history": []
            }
        else:
            # Skip this stage
            print(f"[advance_to_next_step] ✗ Stage {candidate_stage_id} condition NOT satisfied, skipping")
    
    # No more stages with satisfied conditions, workflow completed
    print(f"[advance_to_next_step] No more stages with satisfied conditions, marking workflow as completed")
    return {**state, "completed": True}
